<?xml version="1.0"?>
<!--
Parameters:
- offsets
    - neck to shoulder
    - shoulder to elbow
    - elbow to wrist

- joint limits (source: https://design.tutsplus.com/articles/human-anatomy-fundamentals-flexibility-and-joint-limitations-vector-25401)
    - shoulder
        - abduction 180
        - adduction -45
        - horizontal flexion 130
        - horizontal extension -45
        - vertical flexion 180
        - vertical extension -60
    - elbow
        - flexion -150
        - extension 0
        - supination 180
        - pronation -90

    - wrist
        - extension 70
        - flexion 90
        - radial 20
        - ulnar 50

-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="human_torso">
    <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>

    <!--<xacro:property name="models_path" value="file:///home/jfelip/workspace/prob-comp-code/manipulator_planning_control/models" />-->
    <!--<xacro:property name="models_path" value="/home/jfelip/workspace/prob-comp-code/manipulator_planning_control/models" />-->
    <xacro:property name="models_path" value="./" />

<xacro:macro name="human_head" params="prefix base_link joint_type *origin">

    <xacro:property name="head_width" value="0.27" />
    <xacro:property name="head_height" value="0.4" />
    <xacro:property name="head_depth" value="0.32" />

    <xacro:property name="tilt_up_limit" value="0.95993" />
    <xacro:property name="tilt_down_limit" value="1.57079" />
    <xacro:property name="tilt_effort" value="1000.0" />
    <xacro:property name="tilt_velocity" value="0.5" />

    <xacro:property name="roll_limit" value="0.61086" />
    <xacro:property name="roll_effort" value="1000.0" />
    <xacro:property name="roll_velocity" value="0.5" />

    <xacro:property name="pan_limit" value="1.22173" />
    <xacro:property name="pan_effort" value="1000.0" />
    <xacro:property name="pan_velocity" value="0.5" />

    <link name="${prefix}head_roll">
        <visual>
            <geometry>
                <mesh filename="${models_path}/head.obj"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${head_depth} ${head_width} ${head_height}"/>
            </geometry>
            <origin xyz="0.03 0 ${head_height/2 - 0.02}" rpy="0 0 0"/>
        </collision>

        <inertial>
           <mass value="5.0" />
           <origin xyz="0 0 0" rpy="0 0 0"/>
           <inertia ixx="0.5"  ixy="0"  ixz="0" iyy="0.5" iyz="0" izz="0.5" />
        </inertial>
    </link>

    <link name="${prefix}head_tilt">
        <inertial>
           <mass value="0.01" />
           <origin xyz="0 0 0" rpy="0 0 0"/>
           <inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
        </inertial>
    </link>

    <link name="${prefix}head_pan">
        <inertial>
           <mass value="0.01" />
           <origin xyz="0 0 0" rpy="0 0 0"/>
           <inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
        </inertial>
    </link>


    <joint name="${prefix}pan_joint" type="${joint_type}">
        <axis xyz="0 0 1"/>
        <limit
                effort="${pan_effort}"
                lower="-${pan_limit}"
                upper="${pan_limit}"
                velocity="${pan_velocity}"
        />
        <xacro:insert_block name="origin" />
        <parent link="${base_link}"/>
        <child link="${prefix}head_pan"/>
    </joint>

    <joint name="${prefix}tilt_joint" type="${joint_type}">
        <axis xyz="0 1 0"/>
        <limit
                effort="${tilt_effort}"
                lower="-${tilt_down_limit}"
                upper="${tilt_up_limit}"
                velocity="${tilt_velocity}"
        />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="${prefix}head_pan"/>
        <child link="${prefix}head_tilt"/>
    </joint>

    <joint name="${prefix}roll_joint" type="${joint_type}">
        <axis xyz="1 0 0"/>
        <limit
                effort="${roll_effort}"
                lower="-${roll_limit}"
                upper="${roll_limit}"
                velocity="${roll_velocity}"
        />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="${prefix}head_tilt"/>
        <child link="${prefix}head_roll"/>
    </joint>



</xacro:macro>

<xacro:macro name="human_arm" params="prefix base_link reflect joint_type *origin">

    <xacro:property name="arm_width" value="0.1" />
    <xacro:property name="arm_height" value="0.33" />
    <xacro:property name="arm_depth" value="0.07" />

    <xacro:property name="forearm_width" value="0.07" />
    <xacro:property name="forearm_height" value="0.2" />
    <xacro:property name="forearm_depth" value="0.07" />

    <xacro:property name="palm_width" value="0.16" />
    <xacro:property name="palm_height" value="0.23" />
    <xacro:property name="palm_depth" value="0.11" />

    <xacro:property name="shoulder_abduction_limit" value="3.1415" />
    <xacro:property name="shoulder_adduction_limit" value="0.1" />
    <xacro:property name="shoulder_abduction_adduction_effort" value="1000.0" />
    <xacro:property name="shoulder_abduction_adduction_velocity" value="2.5" />

    <xacro:property name="shoulder_horizontal_flexion_limit" value="2.26892" />
    <xacro:property name="shoulder_horizontal_extension_limit" value="-0.78539" />
    <xacro:property name="shoulder_horizontal_flexion_extension_effort" value="1000.0" />
    <xacro:property name="shoulder_horizontal_flexion_extension_velocity" value="2.5" />

    <xacro:property name="shoulder_vertical_flexion_limit" value="3.1415" />
    <xacro:property name="shoulder_vertical_extension_limit" value="-1.04719" />
    <xacro:property name="shoulder_vertical_flexion_extension_effort" value="1000.0" />
    <xacro:property name="shoulder_vertical_flexion_extension_velocity" value="2.5" />

    <xacro:property name="elbow_flexion_limit" value="0" />
    <xacro:property name="elbow_extension_limit" value="-2.61799" />
    <xacro:property name="elbow_flexion_extension_effort" value="1000.0" />
    <xacro:property name="elbow_flexion_extension_velocity" value="2.5" />

    <xacro:property name="elbow_pronation_limit" value="-3.1415" />
    <xacro:property name="elbow_supination_limit" value="1.57079" />
    <xacro:property name="elbow_pronation_supination_effort" value="1000.0" />
    <xacro:property name="elbow_pronation_supination_velocity" value="2.5" />

    <xacro:property name="wrist_flexion_limit" value="-1.57079" />
    <xacro:property name="wrist_extension_limit" value="1.22173" />
    <xacro:property name="wrist_flexion_extension_effort" value="1000.0" />
    <xacro:property name="wrist_flexion_extension_velocity" value="2.5" />

    <xacro:property name="wrist_radial_limit" value="-0.34906" />
    <xacro:property name="wrist_ulnar_limit" value="0.87266" />
    <xacro:property name="wrist_radial_ulnar_effort" value="1000.0" />
    <xacro:property name="wrist_radial_ulnar_velocity" value="2.5" />

    <link name="${prefix}shoulder_abduction_adduction">
        <inertial>
           <mass value="0.01" />
           <origin xyz="0 0 0" rpy="0 0 0"/>
           <inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
        </inertial>
    </link>

    <link name="${prefix}shoulder_horizontal_flexion_extension">
        <inertial>
           <mass value="0.01" />
           <origin xyz="0 0 0" rpy="0 0 0"/>
           <inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
        </inertial>
    </link>

    <link name="${prefix}shoulder_vertical_flexion_extension">
        <visual>
            <geometry>
                <mesh filename="${models_path}/${prefix}arm.obj"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${arm_width} ${arm_depth} ${arm_height}"/>
            </geometry>
            <origin xyz="0 ${reflect*0.015} ${-arm_height/2+0.03}" rpy="${reflect*0.1} 0 0"/>
        </collision>

        <inertial>
           <mass value="3.5" />
           <origin xyz="0 0 0" rpy="0 0 0"/>
           <inertia ixx="0.3"  ixy="0"  ixz="0" iyy="0.3" iyz="0" izz="0.3" />
        </inertial>
    </link>

    <link name="${prefix}elbow_flexion_extension">
        <inertial>
           <mass value="0.01" />
           <origin xyz="0 0 0" rpy="0 0 0"/>
           <inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
        </inertial>
    </link>

    <link name="${prefix}elbow_pronation_supination">
        <visual>
            <geometry>
                <mesh filename="${models_path}/${prefix}forearm.obj"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${forearm_width} ${forearm_depth} ${forearm_height}"/>
            </geometry>
            <origin xyz="0.02 ${reflect*0.015} ${-forearm_height/2}" rpy="${reflect*0.2} -0.2 0"/>
        </collision>

        <inertial>
           <mass value="2.5" />
           <origin xyz="0 0 0" rpy="0 0 0"/>
           <inertia ixx="0.2"  ixy="0"  ixz="0" iyy="0.2" iyz="0" izz="0.2" />
        </inertial>
    </link>

    <link name="${prefix}wrist_flexion_extension">
        <inertial>
           <mass value="0.01" />
           <origin xyz="0 0 0" rpy="0 0 0"/>
           <inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
        </inertial>
    </link>

    <link name="${prefix}wrist_radial_ulnar">
        <visual>
            <geometry>
                <mesh filename="${models_path}/${prefix}hand.obj"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <mesh filename="${models_path}/${prefix}hand.obj"/>
                <!--<box size="${palm_width} ${palm_depth} ${palm_height}"/>-->
            </geometry>
            <!--origin xyz="0.025 ${reflect*0.0} ${-palm_height/2 + 0.02}" rpy="0 0 0"/-->
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>

        <inertial>
           <mass value="1.5" />
           <origin xyz="0 0 0" rpy="0 0 0"/>
           <inertia ixx="0.1"  ixy="0"  ixz="0" iyy="0.1" iyz="0" izz="0.1" />
        </inertial>
    </link>

    <joint name="${prefix}shoulder_abduction_adduction_joint" type="${joint_type}">
        <axis xyz="${reflect} 0 0"/>
        <limit
                effort="${shoulder_abduction_adduction_effort}"
                lower="${shoulder_adduction_limit}"
                upper="${shoulder_abduction_limit}"
                velocity="${shoulder_abduction_adduction_velocity}"
        />
        <xacro:insert_block name="origin" />
        <parent link="${base_link}"/>
        <child link="${prefix}shoulder_abduction_adduction"/>
    </joint>

    <joint name="${prefix}shoulder_horizontal_flexion_extension_joint" type="${joint_type}">
        <axis xyz="0 0 ${-1*reflect}"/>
        <limit
            effort="${shoulder_horizontal_flexion_extension_effort}"
            lower="${shoulder_horizontal_extension_limit}"
            upper="${shoulder_horizontal_flexion_limit}"
            velocity="${shoulder_horizontal_flexion_extension_velocity}"
        />
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <parent link="${prefix}shoulder_abduction_adduction"/>
        <child link="${prefix}shoulder_horizontal_flexion_extension"/>
    </joint>

    <joint name="${prefix}shoulder_vertical_flexion_extension_joint" type="${joint_type}">
        <axis xyz="0 -1 0"/>
        <limit
            effort="${shoulder_vertical_flexion_extension_effort}"
            lower="${shoulder_vertical_extension_limit}"
            upper="${shoulder_vertical_flexion_limit}"
            velocity="${shoulder_vertical_flexion_extension_velocity}"
        />
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <parent link="${prefix}shoulder_horizontal_flexion_extension"/>
        <child link="${prefix}shoulder_vertical_flexion_extension"/>
    </joint>

    <joint name="${prefix}elbow_flexion_extension_joint" type="${joint_type}">
        <axis xyz="0 1 0"/>
        <limit
            effort="${elbow_flexion_extension_effort}"
            lower="${elbow_extension_limit}"
            upper="${elbow_flexion_limit}"
            velocity="${elbow_flexion_extension_velocity}"
        />
        <origin rpy="0 0 0" xyz="-0.01223 ${0.03506*reflect} -0.283379"/>
        <parent link="${prefix}shoulder_vertical_flexion_extension"/>
        <child link="${prefix}elbow_flexion_extension"/>
    </joint>

    <joint name="${prefix}elbow_pronation_supination_joint" type="${joint_type}">
        <axis xyz="0 0 -1"/>
        <limit
            effort="${elbow_pronation_supination_effort}"
            lower="${elbow_pronation_limit}"
            upper="${elbow_supination_limit}"
            velocity="${elbow_pronation_supination_velocity}"
        />
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <parent link="${prefix}elbow_flexion_extension"/>
        <child link="${prefix}elbow_pronation_supination"/>
    </joint>

    <joint name="${prefix}wrist_flexion_extension_joint" type="${joint_type}">
        <axis xyz="0 -1 0"/>
        <limit
            effort="${wrist_flexion_extension_effort}"
            lower="${wrist_flexion_limit}"
            upper="${wrist_extension_limit}"
            velocity="${wrist_flexion_extension_velocity}"
        />
        <origin rpy="0 0 0" xyz="0.03606 ${0.02363*reflect} -0.19094"/>
        <parent link="${prefix}elbow_pronation_supination"/>
        <child link="${prefix}wrist_flexion_extension"/>
    </joint>

    <joint name="${prefix}wrist_radial_ulnar_joint" type="${joint_type}">
        <axis xyz="${reflect} 0 0"/>
        <limit
            effort="${wrist_radial_ulnar_effort}"
            lower="${wrist_radial_limit}"
            upper="${wrist_ulnar_limit}"
            velocity="${wrist_radial_ulnar_velocity}"
        />
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <parent link="${prefix}wrist_flexion_extension"/>
        <child link="${prefix}wrist_radial_ulnar"/>
    </joint>

    <link name="${prefix}tip">
        <visual>
            <geometry>
                <box size="0.001 0.01 0.001"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.001 0.01 0.001"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>

        <inertial>
           <mass value="0.001" />
           <origin xyz="0 0 0" rpy="0 0 0"/>
           <inertia ixx="0.0001"  ixy="0"  ixz="0" iyy="0.0001" iyz="0" izz="0.0001" />
        </inertial>
    </link>

    <joint name="${prefix}tip_joint" type="fixed">
        <origin rpy="0 ${3.1415*reflect} 0" xyz="0.03 ${0.015*reflect} -${palm_height}"/>
        <parent link="${prefix}wrist_radial_ulnar"/>
        <child link="${prefix}tip"/>
    </joint>

</xacro:macro>


    <xacro:property name="torso_depth" value="0.2" />
    <xacro:property name="torso_width" value="0.22" />
    <xacro:property name="torso_height" value="0.59" />
    <xacro:property name="torso_joint_type" value="revolute" />
    <link name="base_link">
        <inertial>
           <mass value="0.01" />
           <origin xyz="0 0 0" rpy="0 0 0"/>
           <inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
        </inertial>
    </link>


    <link name="torso_pan">
        <inertial>
           <mass value="0.01" />
           <origin xyz="0 0 0" rpy="0 0 0"/>
           <inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
        </inertial>
    </link>

    <link name="torso">
        <visual>
            <geometry>
                <mesh filename="${models_path}/torso.obj"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${torso_depth} ${torso_width} ${torso_height}"/>
            </geometry>
            <origin xyz="0 0 ${torso_height/2}" rpy="0 0 0"/>
        </collision>
        <inertial>
           <mass value="40.0" />
           <origin xyz="0 0 0" rpy="0 0 0"/>
           <inertia ixx="4.0"  ixy="0"  ixz="0" iyy="4.0" iyz="0" izz="4.0" />
        </inertial>
    </link>

    <joint name="torso_pan_joint" type="${torso_joint_type}">
        <axis xyz="0 0 1"/>
        <limit
            effort="10000.0"
            lower="-1.22173"
            upper="1.22173"
            velocity="1.57"
        />
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <parent link="base_link"/>
        <child link="torso_pan"/>
    </joint>

    <joint name="torso_tilt_joint" type="${torso_joint_type}">
        <axis xyz="0 1 0"/>
        <limit
            effort="10000.0"
            lower="-0.32173"
            upper="0.32173"
            velocity="1.57"
        />
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <parent link="torso_pan"/>
        <child link="torso"/>
    </joint>

    <xacro:human_arm prefix="l_" base_link="torso" reflect="1" joint_type="revolute">
        <origin xyz=" 0 0.10988 0.4938" rpy="0 0 0" />
    </xacro:human_arm>

    <xacro:human_arm prefix="r_" base_link="torso" reflect="-1" joint_type="fixed">
        <origin xyz=" -0.00304 -0.10786 0.49489" rpy="0 0 0" />
    </xacro:human_arm>

    <xacro:human_head prefix="head_" base_link="torso" joint_type="fixed">
        <origin xyz=" 0.0255 0 0.59" rpy="0 0 0" />
    </xacro:human_head>


</robot>